# SonarQube Local Analysis Configuration
sonar.projectKey=nuxeo_nuxeo-admin-console-ui
sonar.organization=nuxeo
sonar.projectName=nuxeo-admin-console-ui

# Source code
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.spec.ts,**/dist/**,**/node/**

# TypeScript/JavaScript
sonar.typescript.lcov.reportPaths=coverage/admin_console_ui/lcov.info
sonar.javascript.lcov.reportPaths=coverage/admin_console_ui/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

