name: Save Secrets on PR to Dev

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened

jobs:
  save-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create secrets file
        run: |
          echo "SECRET_KEY=${{ secrets.CONNECT_AUTH }}" > secrets.txt

      - name: Upload secrets as artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.txt
          retention-days: 1  # Keep artifact for 7 days
